version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ${WEBAPP_STORAGE_HOME}/uploads:/directus/uploads
      - ${WEBAPP_STORAGE_HOME}/database:/directus/database
    environment:
      KEY: '<Random UID>'
      SECRET: '<Random UID>'

      DB_CLIENT: 'mysql'
      DB_HOST: '<your host >'
      DB_PORT: '<your port>'
      DB_DATABASE: '<your db>'
      DB_USER: 'directus'
      DB_PASSWORD: '<Your password>'


      ADMIN_EMAIL: '<the mail adress to login in the gui>'
      ADMIN_PASSWORD: '<the defaul password to be changed after 1 deployment>'